server:
  port: 3111
spring:
  application:
    name: MedTracker_v1_thymeleaf
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2DBs/medtracker_thymeleaf;AUTO_SERVER=TRUE


