drop table if exists bloodpressurereading cascade 
drop table if exists dailyevaluation cascade 
drop table if exists dose cascade 
drop table if exists evaluationentry cascade 
drop table if exists medication cascade 
drop table if exists practitionerrolerequest cascade 
drop table if exists prescription cascade 
drop table if exists prescriptionscheduleentry cascade 
drop table if exists usermodel cascade 