INSERT INTO USERMODEL (username, password, role)
SELECT 'admin@admin.com', '$2a$10$WSU4n.NhUE7g1lwMAeTT9OXAaGJG2s.4UkhYIYuIcT0qn0AxNV8NO', 'ADMIN'
WHERE
NOT EXISTS (
    SELECT username FROM USERMODEL WHERE username = 'admin@admin.com'
);

INSERT INTO USERMODEL (username, password, role)
SELECT 'doc@doc.com', '$2a$10$WSU4n.NhUE7g1lwMAeTT9OXAaGJG2s.4UkhYIYuIcT0qn0AxNV8NO', 'PRACT'
WHERE
NOT EXISTS (
    SELECT username FROM USERMODEL WHERE username = 'doc@doc.com'
);

INSERT INTO USERMODEL (username, password, role)
SELECT 'patient1@pat.com', '$2a$10$WSU4n.NhUE7g1lwMAeTT9OXAaGJG2s.4UkhYIYuIcT0qn0AxNV8NO', 'USER'
WHERE
NOT EXISTS (
    SELECT username FROM USERMODEL WHERE username = 'patient1@pat.com'
);
INSERT INTO USERMODEL (username, password, role)
SELECT 'patient2@pat.com', '$2a$10$WSU4n.NhUE7g1lwMAeTT9OXAaGJG2s.4UkhYIYuIcT0qn0AxNV8NO', 'USER'
WHERE
NOT EXISTS (
    SELECT username FROM USERMODEL WHERE username = 'patient2@pat.com'
);

INSERT INTO PRACTITIONERROLEREQUEST (USERMODEL_ID, APPROVED)
SELECT '2', 'TRUE'
WHERE
NOT EXISTS (
    SELECT USERMODEL_ID FROM PRACTITIONERROLEREQUEST WHERE USERMODEL_ID = '2'
);

INSERT INTO MEDICATION ( NAME)
SELECT 'FOO_MED'
WHERE
NOT EXISTS (
    SELECT ID FROM MEDICATION WHERE ID = '1'
);

INSERT INTO PRESCRIPTION ( MEDICATION_ID, PATIENT_ID, PRACTITIONER_ID, BEGIN_TIME, END_TIME, DOSE_MG)
SELECT '1','3', '2', {ts '2024-12-01 10:34:53'}, {ts '2024-12-01 10:34:53'}, '15'
WHERE
NOT EXISTS (
    SELECT PATIENT_ID FROM PRESCRIPTION WHERE PATIENT_ID = '3'
);
INSERT INTO PRESCRIPTIONSCHEDULEENTRY (DAY_STAGE, PRESCRIPTION_ID)
SELECT 'BEDTIME', '1'
WHERE
NOT EXISTS (
    SELECT PRESCRIPTION_ID FROM PRESCRIPTIONSCHEDULEENTRY WHERE PRESCRIPTION_ID = '1' AND DAY_STAGE = 'BEDTIME'
);



INSERT INTO DAILYEVALUATION (USERMODEL_ID, RECORD_DATE)
SELECT '1', {ts '2024-12-01'}
WHERE
NOT EXISTS (
    SELECT USERMODEL_ID FROM DAILYEVALUATION WHERE USERMODEL_ID = '1'
);

INSERT INTO DOSE (DOSE_TIME, TAKEN, dailyevaluation_record_Date,dailyevaluation_userModel_id,prescription_schedule_entry_id)
SELECT {ts '2024-12-01 10:34:53'},'TRUE', {ts '2024-12-01'},'1','1'
WHERE
NOT EXISTS (
    SELECT ID FROM DOSE WHERE ID = '1'
);
INSERT INTO BLOODPRESSUREREADING (dailyevaluation_record_Date,dailyevaluation_userModel_id,prescription_schedule_entry_id, systole, diastole, heart_rate, reading_time)
SELECT  {ts '2024-12-01'},'1','1','111','77','66', {ts '2024-12-01 10:34:53'}
WHERE
NOT EXISTS (
    SELECT ID FROM BLOODPRESSUREREADING WHERE ID = '1'
);







-- all password in plaintext are 'abc'