create table if not exists evaluationEntry (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_Date date,
    blood_pressure_systole int,
    blood_pressure_diastole int,
    heart_rate int
);