create type if not exists USER_ROLE as enum('ADMIN', 'PRACT', 'USER');
create type if not exists DRUG as enum('FOO', 'BAR');
create type if not exists DAYSTAGE as enum('BREAKFAST', 'LUNCH','SECONDPEAK');

create table if not exists USERMODEL (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255),
    password varchar(255),
    role USER_ROLE
);

create table if not exists evaluationEntry (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_Date date,
    medication varchar(255),
    dose1 int,
    dose2 int,
    blood_pressure_systole int,
    blood_pressure_diastole int,
    heart_rate int,
    lunch_blood_pressure_systole int,
    lunch_blood_pressure_diastole int,
    lunch_heart_rate int,
    sdp_blood_pressure_systole int,
    sdp_blood_pressure_diastole int,
    sdp_heart_rate int,
    userModel_id int,
    foreign key (userModel_id) references userModel(id)
);

create table if not exists DAILYEVALUATION (
    record_Date date,
    userModel_id int,
    foreign key (userModel_id) references userModel(id)
);

create table if not exists PRACTITIONERROLEREQUEST (
    approved bit,
    userModel_id int,
    constraint PK_PRACTITIONERROLEREQUEST primary key (userModel_id),
    foreign key (userModel_id) references userModel(id)
);

create table if not exists PRESCRIPTION (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug DRUG,
    dose_mg int,
    patient_id int,
    foreign key (patient_id) references userModel(id),
    practitioner_id int,
    foreign key (practitioner_id) references userModel(id),
    begin_time timestamp,
    end_time timestamp
);

create table if not exists MEDICATION (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255)
);



create table if not exists PRESCRIPTIONSCHEDULEENTRY (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_stage DAYSTAGE,
    prescription_id int,
    foreign key (prescription_id) references prescription(id)

);